import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./globals.css";
import theme from "./theme/theme";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import { ThemeProvider } from '@mui/material/styles';


const inter = Inter({ subsets: ["latin"] });
const poppins = Poppins({
  subsets: ["latin"],
  weight: "500",
  display: "swap",
  style: "normal",
  
});

export const metadata: Metadata = {
  title: "Obralink",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={poppins.className}>{children}</body>
    </html>
  );
}
